import { contextBridge, ipcRenderer } from 'electron';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import type { KZApi } from '../shared/api';
const iconPath=()=>process.defaultApp?path.join(process.cwd(),'build','Aurora-IDE.png'):path.join(process.resourcesPath,'Aurora-IDE.png');
const api:KZApi={
 workspace:{open:()=>ipcRenderer.invoke('workspace:open'),last:()=>ipcRenderer.invoke('workspace:last'),readTree:root=>ipcRenderer.invoke('workspace:tree',root)},
 file:{read:p=>ipcRenderer.invoke('file:read',p),write:(p,c)=>ipcRenderer.invoke('file:write',p,c),create:(p,k)=>ipcRenderer.invoke('file:create',p,k),remove:p=>ipcRenderer.invoke('file:remove',p),rename:(a,b)=>ipcRenderer.invoke('file:rename',a,b)},
 terminal:{cwd:()=>ipcRenderer.invoke('terminal:cwd'),run:(c,cwd)=>ipcRenderer.invoke('terminal:run',c,cwd)},
 git:{status:cwd=>ipcRenderer.invoke('git:status',cwd),diff:(cwd,f)=>ipcRenderer.invoke('git:diff',cwd,f),run:(cwd,args)=>ipcRenderer.invoke('git:run',cwd,args)},
 search:{workspace:(root,q)=>ipcRenderer.invoke('search:workspace',root,q)},settings:{get:()=>ipcRenderer.invoke('settings:get'),save:p=>ipcRenderer.invoke('settings:save',p)},
 dev:{project:root=>ipcRenderer.invoke('dev:project',root),tests:(root,c)=>ipcRenderer.invoke('dev:tests',root,c),run:(root,c)=>ipcRenderer.invoke('dev:run',root,c),debug:(root,c)=>ipcRenderer.invoke('dev:debug',root,c),diagnostics:root=>ipcRenderer.invoke('dev:diagnostics',root),debugger:{start:(root,c)=>ipcRenderer.invoke('debug:start',root,c),breakpoint:(id,file,line)=>ipcRenderer.invoke('debug:breakpoint',id,file,line),command:(id,c)=>ipcRenderer.invoke('debug:command',id,c),snapshot:id=>ipcRenderer.invoke('debug:snapshot',id),onEvent:callback=>{const listener=(_e:Electron.IpcRendererEvent,s:Parameters<typeof callback>[0])=>callback(s);ipcRenderer.on('debug:event',listener);return()=>ipcRenderer.removeListener('debug:event',listener);}}},
 update:{status:()=>ipcRenderer.invoke('update:status'),check:()=>ipcRenderer.invoke('update:check'),download:()=>ipcRenderer.invoke('update:download'),install:()=>{void ipcRenderer.invoke('update:install')},onStatus:callback=>{const listener=(_e:Electron.IpcRendererEvent,s:Parameters<typeof callback>[0])=>callback(s);ipcRenderer.on('update:status',listener);return()=>ipcRenderer.removeListener('update:status',listener)}},
 collab:{status:()=>ipcRenderer.invoke('collab:status'),host:(root,nickname,port)=>ipcRenderer.invoke('collab:host',root,nickname,port),join:(root,url,token,nickname)=>ipcRenderer.invoke('collab:join',root,url,token,nickname),sync:()=>ipcRenderer.invoke('collab:sync'),edit:(p,c,v)=>ipcRenderer.invoke('collab:edit',p,c,v),cursor:c=>ipcRenderer.invoke('collab:cursor',c),setRole:(id,role)=>ipcRenderer.invoke('collab:role',id,role),kick:id=>ipcRenderer.invoke('collab:kick',id),chat:text=>ipcRenderer.invoke('collab:chat',text),leave:()=>ipcRenderer.invoke('collab:leave'),onEvent:callback=>{const listener=(_e:Electron.IpcRendererEvent,event:Parameters<typeof callback>[0])=>callback(event);ipcRenderer.on('collab:event',listener);return()=>ipcRenderer.removeListener('collab:event',listener);}},
 window:{minimize:()=>{void ipcRenderer.invoke('window:minimize')},toggleMaximize:()=>{void ipcRenderer.invoke('window:toggle-maximize')},close:()=>{void ipcRenderer.invoke('window:close')},icon:()=>pathToFileURL(iconPath()).href}
};
contextBridge.exposeInMainWorld('kz',api);