import { contextBridge, ipcRenderer } from 'electron';
import type { KZApi } from '../shared/api';
const api:KZApi={
 workspace:{open:()=>ipcRenderer.invoke('workspace:open'),last:()=>ipcRenderer.invoke('workspace:last'),readTree:root=>ipcRenderer.invoke('workspace:tree',root)},
 file:{read:p=>ipcRenderer.invoke('file:read',p),write:(p,c)=>ipcRenderer.invoke('file:write',p,c),create:(p,k)=>ipcRenderer.invoke('file:create',p,k),remove:p=>ipcRenderer.invoke('file:remove',p),rename:(a,b)=>ipcRenderer.invoke('file:rename',a,b)},
 terminal:{cwd:()=>ipcRenderer.invoke('terminal:cwd'),run:(c,cwd)=>ipcRenderer.invoke('terminal:run',c,cwd)},
 git:{status:cwd=>ipcRenderer.invoke('git:status',cwd),diff:(cwd,f)=>ipcRenderer.invoke('git:diff',cwd,f),run:(cwd,args)=>ipcRenderer.invoke('git:run',cwd,args)},
 search:{workspace:(root,q)=>ipcRenderer.invoke('search:workspace',root,q)},settings:{get:()=>ipcRenderer.invoke('settings:get'),save:p=>ipcRenderer.invoke('settings:save',p)},
 dev:{project:root=>ipcRenderer.invoke('dev:project',root),tests:(root,c)=>ipcRenderer.invoke('dev:tests',root,c),run:(root,c)=>ipcRenderer.invoke('dev:run',root,c),debug:(root,c)=>ipcRenderer.invoke('dev:debug',root,c),diagnostics:root=>ipcRenderer.invoke('dev:diagnostics',root),debugger:{start:(root,c)=>ipcRenderer.invoke('debug:start',root,c),breakpoint:(id,file,line)=>ipcRenderer.invoke('debug:breakpoint',id,file,line),command:(id,c)=>ipcRenderer.invoke('debug:command',id,c),snapshot:id=>ipcRenderer.invoke('debug:snapshot',id),onEvent:callback=>{const listener=(_e:Electron.IpcRendererEvent,s:Parameters<typeof callback>[0])=>callback(s);ipcRenderer.on('debug:event',listener);return()=>ipcRenderer.removeListener('debug:event',listener);}}},
 update:{status:()=>ipcRenderer.invoke('update:status'),check:()=>ipcRenderer.invoke('update:check'),download:()=>ipcRenderer.invoke('update:download'),install:()=>{void ipcRenderer.invoke('update:install')},onStatus:callback=>{const listener=(_e:Electron.IpcRendererEvent,s:Parameters<typeof callback>[0])=>callback(s);ipcRenderer.on('update:status',listener);return()=>ipcRenderer.removeListener('update:status',listener)}}
};
contextBridge.exposeInMainWorld('kz',api);