import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { BrowserWindow } from 'electron';
import type { WebSocket } from 'ws';
import WebSocketClient from 'ws';
import path from 'node:path';

export type DebugFrame={id:number;name:string;file:string;line:number;column:number};
export type DebugVariable={name:string;value:string;type?:string};
export type DebugSnapshot={state:'starting'|'paused'|'running'|'stopped'|'error';frames:DebugFrame[];variables:DebugVariable[];message?:string};

type Session={id:string;child:ChildProcessWithoutNullStreams;socket:WebSocket|null;next:number;pending:Map<number,(v:any)=>void>;breakpoints:Array<{file:string;line:number}>;snapshot:DebugSnapshot};
const sessions=new Map<string,Session>();
const emit=(snapshot:DebugSnapshot)=>{for(const w of BrowserWindow.getAllWindows())w.webContents.send('debug:event',snapshot);};
const parse=(s:string)=>s.match(/(?:[^\s"]+|"[^"]*")+/g)?.map(x=>x.replace(/^"|"$/g,''))??[];
const fileUrl=(p:string)=>`file://${p.split(path.sep).map(encodeURIComponent).join('/')}`;

function notify(session:Session,state:DebugSnapshot['state'],patch:Partial<DebugSnapshot>={}){session.snapshot={...session.snapshot,state,...patch};emit(session.snapshot);}
function request(session:Session,method:string,params?:any):Promise<any>{return new Promise(resolve=>{const id=session.next++;session.pending.set(id,resolve);session.socket?.send(JSON.stringify({id,method,params}));});}

async function connect(session:Session,url:string){const ws=new WebSocketClient(url);session.socket=ws;ws.on('message',async raw=>{const msg=JSON.parse(String(raw));if(msg.id){const done=session.pending.get(msg.id);if(done){session.pending.delete(msg.id);done(msg.result??msg);}}if(msg.method==='Debugger.paused'){const frames=(msg.params.callFrames??[]).map((f:any)=>({id:f.callFrameId,name:f.functionName||'(anonymous)',file:f.url?decodeURIComponent(f.url.replace(/^file:\/\//,'')):'',line:(f.location?.lineNumber??0)+1,column:(f.location?.columnNumber??0)+1}));let variables:DebugVariable[]=[];const scope=msg.params.callFrames?.[0]?.scopeChain?.find((s:any)=>s.type==='local');if(scope?.object?.objectId){const r=await request(session,'Runtime.getProperties',{objectId:scope.object.objectId,ownProperties:true});variables=(r.result??[]).map((p:any)=>({name:p.name,value:p.value?.value!==undefined?String(p.value.value):p.value?.description??p.value?.type??'undefined',type:p.value?.type}));}notify(session,'paused',{frames,variables,message:msg.params.reason??'breakpoint'});}if(msg.method==='Debugger.resumed')notify(session,'running',{frames:[],variables:[]});if(msg.method==='Runtime.executionContextDestroyed')notify(session,'running');});ws.on('error',e=>notify(session,'error',{message:String(e)}));ws.on('close',()=>{session.socket=null;if(session.snapshot.state!=='stopped')notify(session,'stopped',{frames:[],variables:[]});});await new Promise<void>((resolve,reject)=>{ws.once('open',()=>resolve());ws.once('error',reject);});await request(session,'Runtime.enable');await request(session,'Debugger.enable');for(const bp of session.breakpoints)await request(session,'Debugger.setBreakpointByUrl',{lineNumber:bp.line-1,url:fileUrl(bp.file)});await request(session,'Runtime.runIfWaitingForDebugger');notify(session,'running',{frames:[],variables:[]});}

export async function startNodeDebug(root:string,command?:string){const args=parse(command??'');if(args[0]!=='node'){return {ok:false,message:'O debugger interativo 0.7 usa o inspector nativo do Node. Configure .kzide/launch.json com command: node.'};}const nodeArgs=args.slice(1);const id=`dbg-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const child=spawn(process.execPath,['--inspect-brk=0',...nodeArgs],{cwd:root,env:process.env,stdio:'pipe'});const session:Session={id,child,socket:null,next:1,pending:new Map(),breakpoints:[],snapshot:{state:'starting',frames:[],variables:[]}};sessions.set(id,session);let connected=false;const connectFromStderr=async(data:Buffer)=>{const m=data.toString().match(/ws:\/\/(127\.0\.0\.1:\d+)\/[\w-]+/);if(m&&!connected){connected=true;const list=await fetch(`http://${m[1]}/json/list`).then(r=>r.json() as Promise<any[]>);const wsUrl=list[0]?.webSocketDebuggerUrl;if(wsUrl)await connect(session,wsUrl);else notify(session,'error',{message:'Não foi possível localizar o WebSocket do inspector.'});}};child.stderr.on('data',d=>void connectFromStderr(d));child.stdout.on('data',d=>emit({...session.snapshot,message:String(d)}));child.on('exit',code=>{notify(session,'stopped',{frames:[],variables:[],message:`processo finalizado (${code??0})`});sessions.delete(id);});child.on('error',e=>notify(session,'error',{message:e.message}));return {ok:true,id};}
export async function setBreakpoint(id:string,file:string,line:number){const s=sessions.get(id);if(!s)return false;s.breakpoints.push({file:path.resolve(file),line});if(s.socket)await request(s,'Debugger.setBreakpointByUrl',{lineNumber:line-1,url:fileUrl(path.resolve(file))});return true;}
export async function debugCommand(id:string,command:'continue'|'pause'|'next'|'stepIn'|'stepOut'|'stop'){const s=sessions.get(id);if(!s)return false;if(command==='stop'){s.socket?.close();s.child.kill();sessions.delete(id);emit({state:'stopped',frames:[],variables:[],message:'sessão encerrada'});return true;}const methods={continue:'Debugger.resume',pause:'Debugger.pause',next:'Debugger.stepOver',stepIn:'Debugger.stepInto',stepOut:'Debugger.stepOut'} as const;await request(s,methods[command]);return true;}
export function debugSnapshot(id:string){return sessions.get(id)?.snapshot??null;}
