import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync = promisify(execFile);
const TIMEOUT_MS = 120_000;
const MAX_BUFFER = 8 * 1024 * 1024;
export type ToolResult = { stdout: string; stderr: string; code: number | null };
export type ProjectInfo = { root: string; kind: string; packageManager?: string; testCommand?: string; runCommand?: string; debugCommand?: string };
export type Diagnostic = { line: number; column: number; message: string; severity: 'error'|'warning'|'info'; source: string };
const exists = async (p: string) => { try { await fs.access(p); return true; } catch { return false; } };
async function run(program: string, args: string[], cwd: string): Promise<ToolResult> { try { const r = await execFileAsync(program,args,{cwd,timeout:TIMEOUT_MS,maxBuffer:MAX_BUFFER,windowsHide:true}); return {stdout:r.stdout??'',stderr:r.stderr??'',code:0}; } catch (e:any) { return {stdout:String(e?.stdout??''),stderr:String(e?.stderr??e?.message??''),code:typeof e?.code==='number'?e.code:1}; } }
function splitCommand(s:string){ return (s.match(/(?:[^\s"]+|"[^"]*")+/g)??[]).map(x=>x.replace(/^"|"$/g,'')); }
export async function detectProject(root:string):Promise<ProjectInfo>{ const base=path.resolve(root); if(await exists(path.join(base,'package.json'))){ let pkg:any={}; try{pkg=JSON.parse(await fs.readFile(path.join(base,'package.json'),'utf8'));}catch{} const pm=await exists(path.join(base,'pnpm-lock.yaml'))?'pnpm':await exists(path.join(base,'yarn.lock'))?'yarn':await exists(path.join(base,'bun.lock'))||await exists(path.join(base,'bun.lockb'))?'bun':'npm'; const script=(n:string)=>pkg?.scripts?.[n] as string|undefined; return {root:base,kind:'node',packageManager:pm,testCommand:script('test')?`${pm} test`:undefined,runCommand:script('start')?`${pm} start`:script('dev')?`${pm} run dev`:undefined,debugCommand:script('debug')?`${pm} run debug`:undefined}; } if(await exists(path.join(base,'Cargo.toml')))return{root:base,kind:'rust',testCommand:'cargo test',runCommand:'cargo run',debugCommand:'rust-gdb'}; if(await exists(path.join(base,'go.mod')))return{root:base,kind:'go',testCommand:'go test ./...',runCommand:'go run .',debugCommand:'dlv debug'}; if(await exists(path.join(base,'pyproject.toml'))||await exists(path.join(base,'pytest.ini')))return{root:base,kind:'python',testCommand:'python -m pytest',runCommand:'python -m',debugCommand:'python -m debugpy'}; if(await exists(path.join(base,'Makefile')))return{root:base,kind:'make',testCommand:'make test',runCommand:'make run'}; return{root:base,kind:'generic'}; }
export async function runTests(root:string,command?:string){const p=await detectProject(root);const c=command?.trim()||p.testCommand;if(!c)return{...p,command:null,result:{stdout:'',stderr:'Nenhum comando de testes detectado.',code:1}};const [program,...args]=splitCommand(c);return{...p,command:c,result:await run(program,args,p.root)};}
export async function runProject(root:string,command?:string){const p=await detectProject(root);const c=command?.trim()||p.runCommand;if(!c)return{...p,command:null,result:{stdout:'',stderr:'Nenhum comando de execução detectado.',code:1}};const [program,...args]=splitCommand(c);return{...p,command:c,result:await run(program,args,p.root)};}
export async function debugProject(root:string,command?:string){const p=await detectProject(root);const c=command?.trim()||p.debugCommand;if(!c)return{...p,command:null,result:{stdout:'',stderr:'Nenhum depurador configurado para este projeto.',code:1}};const [program,...args]=splitCommand(c);return{...p,command:c,result:await run(program,args,p.root)};}
export async function diagnostics(root:string):Promise<Diagnostic[]>{const p=await detectProject(root);const out:Diagnostic[]=[];if(p.kind==='node'){try{JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));}catch(e){out.push({line:1,column:1,message:`package.json inválido: ${e instanceof Error?e.message:String(e)}`,severity:'error',source:'json'});}const tsc=path.join(root,'node_modules','.bin','tsc');if(await exists(tsc)){const r=await run(tsc,['--noEmit','--pretty','false'],root);for(const line of r.stdout.split('\n').concat(r.stderr.split('\n'))){const m=line.match(/^(.*)\((\d+),(\d+)\):\s+(error|warning)\s+(TS\d+):\s*(.*)$/);if(m)out.push({line:+m[2],column:+m[3],message:`${m[5]}: ${m[6]}`,severity:m[4]==='error'?'error':'warning',source:'tsc'});}}}if(p.kind==='rust'){const r=await run('cargo',['check','--message-format','short'],root);for(const line of r.stderr.split('\n').concat(r.stdout.split('\n'))){const m=line.match(/^(.*):(\d+):(\d+):\s*(error|warning):\s*(.*)$/);if(m)out.push({line:+m[2],column:+m[3],message:m[5],severity:m[4]==='error'?'error':'warning',source:'cargo'});}}return out;}
