type Status = { state: string; url?: string; token?: string; peers: number; nickname?: string; message?: string };
const el = <T extends HTMLElement>(tag: string, className: string, text = '') => { const node = document.createElement(tag) as T; node.className = className; node.textContent = text; return node; };
const cssEscape = (value: string) => value.replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c] ?? c));
let panel: HTMLDivElement | null = null;
let messages: HTMLDivElement | null = null;
const close = () => { panel?.remove(); panel = null; };
const button = (text: string, action: () => void, primary = false) => { const b = el<HTMLButtonElement>('button', `collab-btn${primary ? ' primary' : ''}`, text); b.onclick = action; return b; };
const input = (placeholder: string, value = '') => { const i = el<HTMLInputElement>('input', 'collab-input'); i.placeholder = placeholder; i.value = value; return i; };
const showStatus = (status: Status) => { if (!panel) return; const badge = panel.querySelector<HTMLElement>('.collab-status'); if (badge) { badge.textContent = status.state === 'hosting' ? `● Hospedando · ${status.peers} conectado(s)` : status.state === 'connected' ? '● Conectado' : '○ Offline'; badge.dataset.state = status.state; } };
const addMessage = (payload: any) => { if (!messages || !payload) return; const row = el<HTMLDivElement>('div', 'collab-message'); row.innerHTML = `<strong>${cssEscape(String(payload.nickname ?? 'Aurora'))}</strong><span>${cssEscape(String(payload.text ?? ''))}</span>`; messages.appendChild(row); messages.scrollTop = messages.scrollHeight; };
const openPanel = async () => {
 if (panel) return;
 const root = (await window.kz.workspace.last()).workspace;
 panel = el<HTMLDivElement>('div', 'collab-panel');
 const card = el<HTMLDivElement>('div', 'collab-card');
 const head = el<HTMLDivElement>('div', 'collab-head'); head.append(el('div','collab-title','Collaboration'), button('×', close));
 const status = el<HTMLDivElement>('div','collab-status','○ Offline'); status.dataset.state='idle';
 const tabs = el<HTMLDivElement>('div','collab-tabs'); const hostTab=button('Hospedar',()=>hostForm()); const joinTab=button('Entrar',()=>joinForm()); tabs.append(hostTab,joinTab);
 messages = el<HTMLDivElement>('div','collab-messages');
 const body = el<HTMLDivElement>('div','collab-body');
 const hostForm = () => { body.replaceChildren(); const name=input('Seu nome','Aurora User'); const port=input('Porta (vazio = automática)'); body.append(el('label','collab-label','Criar sessão'),name,port,button('Criar sessão',async()=>{ if(!root){alert('Abra um workspace primeiro.');return;} try{const s=await window.kz.collab.host(root,name.value,port.value?Number(port.value):undefined); body.replaceChildren(); const url=input('URL da sessão',s.url??''); url.readOnly=true; const tok=input('Token da sessão',s.token??''); tok.readOnly=true; body.append(el('div','collab-hint','Compartilhe a URL e o token com os colaboradores.'),url,tok,button('Sincronizar workspace',async()=>{await window.kz.collab.sync();}),button('Encerrar sessão',async()=>{await window.kz.collab.leave(); close();},false)); showStatus(s);}catch(e){alert(e instanceof Error?e.message:'Falha ao hospedar.');}}),true); };
 const joinForm = () => { body.replaceChildren(); const url=input('ws:// ou wss://'); const tok=input('Token da sessão'); const name=input('Seu nome','Aurora User'); body.append(el('label','collab-label','Entrar em sessão'),url,tok,name,button('Conectar',async()=>{if(!root){alert('Abra um workspace primeiro.');return;} try{const s=await window.kz.collab.join(root,url.value,tok.value,name.value); body.replaceChildren(); body.append(el('div','collab-hint','Conectado. O host controla a sincronização do workspace.'),button('Pedir sincronização',async()=>{await window.kz.collab.sync();}),button('Sair',async()=>{await window.kz.collab.leave();close();})); showStatus(s);}catch(e){alert(e instanceof Error?e.message:'Falha ao conectar.');}}),true); };
 const chat = el<HTMLDivElement>('div','collab-chat'); const msg=input('Mensagem para a equipe'); chat.append(msg,button('Enviar',async()=>{if(msg.value.trim()){await window.kz.collab.chat(msg.value);msg.value='';}}));
 body.append(el('div','collab-hint','Sessões Aurora usam WebSocket seguro por token. Para internet, use wss:// através de um relay/proxy WebSocket.'),el('div','collab-section-title','Sessão'),hostTab);
 card.append(head,status,tabs,body,messages,chat); panel.append(card); document.querySelector('.app')?.append(panel); hostForm();
};
window.addEventListener('collab:event', event => { const detail = (event as CustomEvent).detail; if (detail?.type === 'chat') addMessage(detail.payload); if (detail?.type === 'status') showStatus(detail.payload); });
window.kz.collab.onEvent(event => { if (event.type === 'chat') addMessage(event.payload); if (event.type === 'status') showStatus(event.payload as Status); if (event.type === 'file') { const payload = event.payload as any; addMessage({ nickname:'Aurora', text:`Workspace sincronizado: ${payload?.count ?? 0} arquivo(s).` }); } });
const install = () => { const head=document.querySelector('.sidebar-head'); if(!head || head.querySelector('[data-kz-collab]')) return; const b=el<HTMLButtonElement>('button','collab-trigger','⇄'); b.dataset.kzCollab='true'; b.title='Collaboration'; b.onclick=()=>void openPanel(); head.appendChild(b); };
new MutationObserver(install).observe(document.body,{childList:true,subtree:true}); setTimeout(install,250);