type ToolResult={stdout:string;stderr:string;code:number|null};
type ProjectInfo={root:string;kind:string;packageManager?:string;testCommand?:string;runCommand?:string;debugCommand?:string};
type Diagnostic={line:number;column:number;message:string;severity:'error'|'warning'|'info';source?:string};
type DebugFrame={id:number;name:string;file:string;line:number;column:number};
type DebugVariable={name:string;value:string;type?:string};
type DebugSnapshot={state:'starting'|'paused'|'running'|'stopped'|'error';frames:DebugFrame[];variables:DebugVariable[];message?:string};
declare global{interface Window{ kz:any }}
const style=document.createElement('style');style.textContent=`#kz-dev-toggle{position:fixed;right:10px;top:7px;z-index:9999;border:1px solid #555;background:#0b0b0b;color:#aaa;font:9px monospace;padding:5px 8px;cursor:pointer}#kz-dev-toggle:hover{color:#fff;border-color:#888}#kz-dev-overlay{position:fixed;inset:38px 0 25px;z-index:9998;background:rgba(0,0,0,.72);display:none;font:11px monospace;color:#ddd}#kz-dev-overlay.open{display:flex;justify-content:flex-end}#kz-dev-panel{width:min(820px,94vw);height:100%;background:#0a0a0a;border-left:1px solid #444;display:flex;flex-direction:column}.kz-dev-head{height:38px;border-bottom:1px solid #292929;display:flex;align-items:center;padding:0 12px;gap:16px}.kz-dev-head strong{font-size:10px}.kz-dev-head button{margin-left:auto;border:0;background:transparent;color:#777;cursor:pointer}.kz-dev-toolbar,.kz-debug-row{display:flex;gap:6px;padding:8px 12px;border-bottom:1px solid #292929}.kz-dev-toolbar button,.kz-debug-row button,.kz-dev-command button{border:1px solid #444;background:#111;color:#bbb;padding:6px 9px;font:10px monospace;cursor:pointer}.kz-dev-toolbar button:hover,.kz-debug-row button:hover,.kz-dev-command button:hover{background:#222;color:#fff}.kz-dev-info{padding:8px 12px;color:#777;border-bottom:1px solid #222;line-height:17px}.kz-dev-info b{color:#ccc}.kz-debug-row input{flex:1;min-width:0;background:#080808;border:1px solid #333;color:#ddd;padding:6px;font:10px monospace}.kz-debug-grid{display:grid;grid-template-columns:1fr 1fr;min-height:110px;max-height:240px;border-bottom:1px solid #292929}.kz-debug-pane{overflow:auto;padding:8px 12px;border-right:1px solid #222}.kz-debug-pane:last-child{border-right:0}.kz-debug-pane h4{margin:0 0 6px;color:#666;font-size:8px;letter-spacing:.1em}.kz-debug-item{padding:4px 0;color:#aaa;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kz-debug-item.current{color:#fff}.kz-dev-output{flex:1;overflow:auto;padding:10px 12px;white-space:pre-wrap;color:#aaa}.kz-dev-command{display:flex;gap:6px;padding:9px 12px;border-top:1px solid #292929}.kz-dev-command input{flex:1;background:#080808;border:1px solid #333;color:#ddd;padding:6px;font:10px monospace;outline:none}.kz-dev-diag{padding:7px 0;border-bottom:1px solid #222;cursor:pointer}.kz-dev-diag small{display:block;color:#666;margin-top:3px}`;document.head.appendChild(style);
const toggle=document.createElement('button');toggle.id='kz-dev-toggle';toggle.textContent='DEV';document.body.appendChild(toggle);
const overlay=document.createElement('div');overlay.id='kz-dev-overlay';overlay.innerHTML=`<section id="kz-dev-panel"><header class="kz-dev-head"><strong>RUN & DEBUG</strong><span id="kz-dev-status">idle</span><button id="kz-dev-close">×</button></header><div class="kz-dev-toolbar"><button data-action="run">F5 RUN</button><button data-action="debug">F6 DEBUG</button><button data-action="test">TEST</button><button data-action="diag">DIAGNOSTICS</button><button data-action="clear">CLEAR</button></div><div class="kz-dev-info" id="kz-dev-info">Detectando projeto...</div><div class="kz-debug-row"><input id="kz-break-file" placeholder="arquivo absoluto para breakpoint"/><input id="kz-break-line" type="number" min="1" value="1" style="max-width:70px"/><button id="kz-break-add">BREAK</button></div><div class="kz-debug-row"><button data-debug="continue">CONTINUE</button><button data-debug="pause">PAUSE</button><button data-debug="next">STEP OVER</button><button data-debug="stepIn">STEP IN</button><button data-debug="stepOut">STEP OUT</button><button data-debug="stop">STOP</button></div><div class="kz-debug-grid"><div class="kz-debug-pane"><h4>CALL STACK</h4><div id="kz-stack"></div></div><div class="kz-debug-pane"><h4>LOCALS</h4><div id="kz-vars"></div></div></div><div class="kz-dev-output" id="kz-dev-output"></div><div class="kz-dev-command"><input id="kz-dev-command" placeholder="comando opcional..."/><button id="kz-dev-exec">EXEC</button></div></section>`;document.body.appendChild(overlay);
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;const output=$('kz-dev-output'),info=$('kz-dev-info'),status=$('kz-dev-status'),stack=$('kz-stack'),vars=$('kz-vars');let root:string|null=null;let project:ProjectInfo|null=null;let session:string|null=null;
function print(text:string){output.textContent+=`${text}\n`;output.scrollTop=output.scrollHeight}function setStatus(t:string){status.textContent=t}function esc(v:string){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
async function loadProject(){const state=await window.kz.workspace.last();root=state.workspace;if(!root){project=null;info.textContent='Nenhum workspace aberto.';return}project=await window.kz.dev.project(root);info.innerHTML=`<b>${esc(project.kind)}</b> · ${esc(project.root)}<br>run: ${esc(project.runCommand??'—')} · test: ${esc(project.testCommand??'—')} · debug: ${esc(project.debugCommand??'—')}`}
async function execute(kind:'run'|'debug'|'test',command?:string){if(!root)await loadProject();if(!root)return;setStatus(kind);const r=await window.kz.dev[kind==='test'?'tests':kind](root,command?.trim()||undefined) as {command?:string|null;result:ToolResult};print(`$ ${r.command??'(nenhum comando)'}`);print(r.result.stdout||r.result.stderr||'Concluído.');print(r.result.code===0?'✓ sucesso':`✕ código ${r.result.code}`);setStatus('idle')}
async function showDiagnostics(){if(!root)await loadProject();if(!root)return;setStatus('diagnostics');const ds=await window.kz.dev.diagnostics(root) as Diagnostic[];output.innerHTML='';if(!ds.length){output.textContent='✓ Nenhum diagnóstico encontrado.';setStatus('clean');return}ds.forEach(d=>{const el=document.createElement('div');el.className='kz-dev-diag';el.innerHTML=`${esc(d.message)}<small>${esc(d.source??'tool')} · linha ${d.line}, coluna ${d.column}</small>`;output.appendChild(el)});setStatus(`${ds.length} problemas`)}
function renderDebug(s:DebugSnapshot){setStatus(s.state);stack.innerHTML='';vars.innerHTML='';s.frames.forEach((f,i)=>{const e=document.createElement('div');e.className=`kz-debug-item ${i===0?'current':''}`;e.textContent=`${f.name} · ${f.file||'(runtime)'}:${f.line}:${f.column}`;stack.appendChild(e)});s.variables.forEach(v=>{const e=document.createElement('div');e.className='kz-debug-item';e.textContent=`${v.name} = ${v.value}${v.type?` (${v.type})`:''}`;vars.appendChild(e)});if(s.message)print(`[debug] ${s.message}`)}
async function startDebugger(){if(!root)await loadProject();if(!root)return;setStatus('starting');const cmd=project?.debugCommand;const r=await window.kz.dev.debugger.start(root,cmd);if(!r.ok){print(`✕ ${r.message??'Falha ao iniciar debugger'}`);setStatus('error');return}session=r.id??null;print(`debug session: ${session}`)}
$('kz-break-add').onclick=async()=>{if(!session){await startDebugger();if(!session)return}const file=($('kz-break-file') as HTMLInputElement).value.trim(),line=Number(($('kz-break-line') as HTMLInputElement).value);if(!file||!line)return;const ok=await window.kz.dev.debugger.breakpoint(session,file,line);print(ok?`● breakpoint ${file}:${line}`:'✕ breakpoint falhou')};
overlay.querySelectorAll<HTMLButtonElement>('[data-debug]').forEach(b=>b.onclick=()=>{if(session)void window.kz.dev.debugger.command(session,b.dataset.debug as any)});
window.kz.dev.debugger.onEvent((s:DebugSnapshot)=>renderDebug(s));
toggle.onclick=()=>{overlay.classList.toggle('open');if(overlay.classList.contains('open'))void loadProject()};$('kz-dev-close').onclick=()=>overlay.classList.remove('open');$('kz-dev-exec').onclick=()=>void execute('run',($('kz-dev-command') as HTMLInputElement).value);($('kz-dev-command') as HTMLInputElement).onkeydown=e=>{if(e.key==='Enter')void execute('run',(e.currentTarget as HTMLInputElement).value)};
overlay.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='clear')output.textContent='';else if(a==='diag')void showDiagnostics();else if(a==='run'||a==='debug'||a==='test')void execute(a)});
window.addEventListener('keydown',e=>{if(e.key==='F5'){e.preventDefault();overlay.classList.add('open');void execute('run')}if(e.key==='F6'){e.preventDefault();overlay.classList.add('open');void startDebugger()}if(e.key==='F8'){e.preventDefault();overlay.classList.add('open');void showDiagnostics()}});