import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as monaco from 'monaco-editor';
import type { FileNode, GitStatus } from '../shared/api';
import './styles.css';

type OpenFile = { path: string; name: string; content: string; dirty: boolean };
const languageFor = (name: string) => ({ ts:'typescript',tsx:'typescript',js:'javascript',jsx:'javascript',json:'json',css:'css',html:'html',md:'markdown',py:'python',rs:'rust',go:'go',java:'java',cpp:'cpp',c:'c' } as Record<string,string>)[name.split('.').pop()?.toLowerCase() ?? ''] ?? 'plaintext';

function App() {
  const [root, setRoot] = useState<string|null>(null), [tree,setTree]=useState<FileNode[]>([]), [openFiles,setOpenFiles]=useState<OpenFile[]>([]), [activePath,setActivePath]=useState<string|null>(null);
  const [terminalOpen,setTerminalOpen]=useState(true), [terminalLines,setTerminalLines]=useState<string[]>(['KZ-IDE Terminal','Digite um comando e pressione Enter.']), [command,setCommand]=useState('');
  const [palette,setPalette]=useState(false), [search,setSearch]=useState(false), [searchText,setSearchText]=useState(''), [notice,setNotice]=useState('Pronto'), [gitStatus,setGitStatus]=useState<GitStatus|null>(null), [gitPanel,setGitPanel]=useState(false), [recent,setRecent]=useState<string[]>([]);
  const active=openFiles.find(f=>f.path===activePath)??null;
  const refresh=async(workspace=root)=>{if(!workspace)return;try{setTree(await window.kz.workspace.readTree(workspace));const g=await window.kz.git.status(workspace);setGitStatus(g);}catch(e){setNotice(e instanceof Error?e.message:'Erro ao atualizar workspace.');}};
  const openWorkspace=async()=>{const selected=await window.kz.workspace.open();if(!selected)return;setRoot(selected);setRecent(r=>[selected,...r.filter(x=>x!==selected)].slice(0,8));setOpenFiles([]);setActivePath(null);await refresh(selected);setNotice(selected);};
  const openRecent=async(path:string)=>{setRoot(path);setOpenFiles([]);setActivePath(null);await refresh(path);setNotice(path);};
  const openFile=async(node:FileNode)=>{if(node.kind!=='file')return;const existing=openFiles.find(f=>f.path===node.path);if(existing){setActivePath(node.path);return;}try{const content=await window.kz.file.read(node.path);setOpenFiles(f=>[...f,{path:node.path,name:node.name,content,dirty:false}]);setActivePath(node.path);}catch(e){setNotice(e instanceof Error?e.message:'Erro ao abrir arquivo.');}};
  const saveActive=async()=>{if(!active)return;try{await window.kz.file.write(active.path,active.content);setOpenFiles(fs=>fs.map(f=>f.path===active.path?{...f,dirty:false}:f));await refresh();setNotice('Salvo');}catch(e){setNotice(e instanceof Error?e.message:'Erro ao salvar.');}};
  const createFile=async()=>{if(!root){await openWorkspace();return;}const name=window.prompt('Nome do novo arquivo:','novo.ts');if(!name?.trim())return;await window.kz.file.create(`${root}/${name.trim()}`,'file');await refresh();setNotice(`Criado: ${name.trim()}`);};
  const removeActive=async()=>{if(!active||!window.confirm(`Excluir ${active.name}?`))return;await window.kz.file.remove(active.path);setOpenFiles(fs=>fs.filter(f=>f.path!==active.path));setActivePath(null);await refresh();setNotice('Arquivo removido');};
  const runCommand=async(value:string)=>{const trimmed=value.trim();if(!trimmed)return;const cwd=root??await window.kz.terminal.cwd();setTerminalLines(l=>[...l,`$ ${trimmed}`]);setCommand('');const result=await window.kz.terminal.run(trimmed,cwd);const output=`${result.stdout}${result.stderr}`.trimEnd();setTerminalLines(l=>[...l,...(output?output.split('\n'):['Concluído.']),result.code===0?'✓':`✕ código ${result.code}`]);};
  useEffect(()=>{void window.kz.workspace.last().then(state=>{setRecent(state.recent);if(state.workspace){setRoot(state.workspace);void refresh(state.workspace);}});},[]);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();void saveActive();}if(mod&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();setPalette(true);}if(mod&&e.key.toLowerCase()==='p'){e.preventDefault();setSearch(true);}if(e.key==='Escape'){setPalette(false);setSearch(false);}if(mod&&e.key==='`'){e.preventDefault();setTerminalOpen(o=>!o);}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h);},[active]);
  const flatFiles=useMemo(()=>flatten(tree),[tree]), filtered=searchText?flatFiles.filter(n=>n.name.toLowerCase().includes(searchText.toLowerCase())):flatFiles;
  const gitAction=async(args:string[])=>{if(!root)return;const result=await window.kz.git.run(root,args);setTerminalLines(l=>[...l,`$ git ${args.join(' ')}`,...(result.stdout+result.stderr).trim().split('\n').filter(Boolean),result.code===0?'✓':'✕']);await refresh();};
  return <div className="app"><header className="titlebar"><div className="brand"><span className="brand-mark">KZ</span><strong>KZ-IDE</strong></div><nav className="menu"><button onClick={()=>void openWorkspace()}>File</button><button onClick={()=>setPalette(true)}>Edit</button><button onClick={()=>setSearch(true)}>View</button><button onClick={()=>void saveActive()}>Run</button><button onClick={()=>setTerminalOpen(o=>!o)}>Terminal</button><button>Help</button></nav><div className="workspace-name">{root?root.split(/[\\/]/).pop():'sem workspace'}</div></header>
  <main className="workspace"><aside className="activitybar"><button className="activity active" title="Explorer">▤</button><button className="activity" title="Search" onClick={()=>setSearch(true)}>⌕</button><button className={`activity ${gitPanel?'active':''}`} title="Source Control" onClick={()=>setGitPanel(p=>!p)}>⑂{gitStatus&&!gitStatus.clean&&<i>{gitStatus.files.length}</i>}</button><button className="activity" title="Run and Debug">▷</button><button className="activity" title="Extensions">◇</button></aside>
  <aside className="sidebar">{gitPanel?<GitPanel status={gitStatus} onAction={gitAction}/>:<><div className="sidebar-head"><span>EXPLORER</span><div><button title="Abrir pasta" onClick={()=>void openWorkspace()}>⌂</button><button title="Novo arquivo" onClick={()=>void createFile()}>＋</button></div></div><div className="section-title">{root?root.split(/[\\/]/).pop():'ABRA UM WORKSPACE'}</div>{root?<FileTree nodes={tree} onOpen={openFile}/>:<div className="empty"><p>O KZ-IDE trabalha com pastas reais.</p>{recent.length>0&&<div className="recent"><small>RECENTES</small>{recent.slice(0,5).map(p=><button key={p} onClick={()=>void openRecent(p)}>{p.split(/[\\/]/).pop()}<span>{p}</span></button>)}</div>}<button className="primary" onClick={()=>void openWorkspace()}>Abrir pasta</button></div>}</>}</aside>
  <section className="main-area"><div className="tabs">{openFiles.map(file=><button key={file.path} className={`tab ${file.path===activePath?'active':''}`} onClick={()=>setActivePath(file.path)}><span className="file-dot">{file.dirty?'●':'•'}</span>{file.name}<span className="close" onClick={e=>{e.stopPropagation();setOpenFiles(fs=>fs.filter(f=>f.path!==file.path));if(file.path===activePath)setActivePath(null);}}>×</span></button>)}<button className="new-tab" onClick={()=>setPalette(true)}>＋</button></div><div className="editor">{active?<MonacoEditor file={active} onChange={content=>setOpenFiles(fs=>fs.map(f=>f.path===active.path?{...f,content,dirty:true}:f))}/>:<Welcome onOpen={openWorkspace} onCreate={createFile}/>}</div>{terminalOpen&&<section className="terminal"><div className="panel-tabs"><span className="panel-active">TERMINAL</span><span>OUTPUT</span><span>PROBLEMS</span><button onClick={()=>setTerminalOpen(false)}>×</button></div><div className="terminal-output">{terminalLines.map((line,i)=><div key={`${i}-${line}`}>{line}</div>)}<div className="terminal-input"><span>$</span><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void runCommand(command)}} placeholder="comando..."/></div></div></section>}</section></main>
  <footer className="statusbar"><span>{root?'workspace':'standalone'}</span><span>{active?languageFor(active.name):'KZ'}</span><span className="status-spacer"/><span>{gitStatus?.branch??'sem git'}</span><span>{gitStatus&&!gitStatus.clean?`${gitStatus.files.length} alterações`:'limpo'}</span><span>{notice}</span><button onClick={()=>setTerminalOpen(o=>!o)}>Terminal</button></footer>
  {palette&&<CommandPalette onClose={()=>setPalette(false)} actions={[['Abrir pasta',openWorkspace],['Novo arquivo',createFile],['Salvar arquivo',saveActive],['Alternar terminal',()=>setTerminalOpen(o=>!o)],['Excluir arquivo ativo',removeActive],['Source Control',()=>setGitPanel(true)]]}/>} {search&&<SearchDialog value={searchText} setValue={setSearchText} files={filtered} onOpen={openFile} onClose={()=>{setSearch(false);setSearchText('');}}/>}</div>;
}
function flatten(nodes:FileNode[]):FileNode[]{return nodes.flatMap(n=>n.kind==='folder'?flatten(n.children??[]):[n]);}
function FileTree({nodes,onOpen,depth=0}:{nodes:FileNode[];onOpen:(n:FileNode)=>void;depth?:number}){return <div>{nodes.map(n=><div key={n.path}><button className="tree-item" style={{paddingLeft:`${10+depth*15}px`}} onClick={()=>n.kind==='file'&&onOpen(n)}><span className="tree-icon">{n.kind==='folder'?'▸':'•'}</span><span>{n.name}</span></button>{n.kind==='folder'&&<FileTree nodes={n.children??[]} onOpen={onOpen} depth={depth+1}/>}</div>})}</div>;}
function MonacoEditor({file,onChange}:{file:OpenFile;onChange:(content:string)=>void}){const ref=useRef<HTMLDivElement>(null),change=useRef(onChange);change.current=onChange;useEffect(()=>{if(!ref.current)return;const editor=monaco.editor.create(ref.current,{value:file.content,language:languageFor(file.name),theme:'kz-dark',automaticLayout:true,minimap:{enabled:false},fontSize:13,tabSize:2,padding:{top:14},smoothScrolling:true,scrollBeyondLastLine:false});const d=editor.onDidChangeModelContent(()=>change.current(editor.getValue()));return()=>{d.dispose();editor.dispose();};},[file.path]);return <div ref={ref} className="monaco-host"/>;}
function CommandPalette({actions,onClose}:{actions:Array<[string,()=>void|Promise<void>]>;onClose:()=>void}){const[q,setQ]=useState('');const items=actions.filter(([n])=>n.toLowerCase().includes(q.toLowerCase()));return <div className="overlay"><div className="palette"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite um comando..." onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Enter'&&items[0]){void items[0][1]();onClose();}}}/>{items.map(([n,a])=><button key={n} onClick={()=>{void a();onClose();}}>{n}</button>)}</div></div>;}
function SearchDialog({value,setValue,files,onOpen,onClose}:{value:string;setValue:(v:string)=>void;files:FileNode[];onOpen:(n:FileNode)=>void;onClose:()=>void}){return <div className="overlay"><div className="palette search-dialog"><input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder="Pesquisar arquivo..." onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Enter'&&files[0]){onOpen(files[0]);onClose();}}}/>{files.slice(0,20).map(f=><button key={f.path} onClick={()=>{onOpen(f);onClose();}}>{f.name}<small>{f.path}</small></button>)}</div></div>;}
function GitPanel({status,onAction}:{status:GitStatus|null;onAction:(args:string[])=>void}){return <div className="git-panel"><div className="sidebar-head"><span>SOURCE CONTROL</span></div>{!status?<p className="empty-text">Abra um workspace Git para começar.</p>:<><div className="git-branch">⑂ {status.branch}</div><div className="git-section">{status.clean?'Nenhuma alteração':`${status.files.length} alteração(ões)`}</div>{status.files.map(f=><div className="git-file" key={f.path}><span>{f.status}</span>{f.path}</div>)}{!status.clean&&<button className="primary" onClick={()=>onAction(['diff'])}>Ver diff</button>}<div className="git-actions"><button onClick={()=>onAction(['pull'])}>Pull</button><button onClick={()=>onAction(['push'])}>Push</button><button onClick={()=>onAction(['status'])}>Status</button></div></>}</div>;}
function Welcome({onOpen,onCreate}:{onOpen:()=>void;onCreate:()=>void}){return <div className="welcome"><div className="welcome-mark">KZ</div><h1>KZ-IDE</h1><p>Leve. Tecnológico. Autoral.</p><div className="welcome-actions"><button onClick={onOpen}>Abrir pasta</button><button onClick={onCreate}>Novo arquivo</button></div><div className="shortcuts"><span><b>Ctrl + P</b> Abrir arquivo</span><span><b>Ctrl + Shift + P</b> Comandos</span><span><b>Ctrl + `</b> Terminal</span></div></div>;}
monaco.editor.defineTheme('kz-dark',{base:'vs-dark',inherit:true,rules:[],colors:{'editor.background':'#0b0e12','editor.foreground':'#dbe2ea','editorLineNumber.foreground':'#4e5967','editorLineNumber.activeForeground':'#aab4c1','editorCursor.foreground':'#e5ebf2','editor.selectionBackground':'#26313d'}});
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
